### ISSUE TITLE
TypeError while trying to run start_robot.sh on NUC

### ISSUE THREAD

**Issue by quorty** [intuitive-robots/irl_polymetis#20]
## Starting robot server runs into issue

I have freshly built the recent version of irl_polymetis on the NUC computer and am now trying to use `bash ./scripts/start_robot.sh 201` to connect the workstation PC to the robots. Unfortunately, I get the following error:

```
Adding conda environment libraries to LD_LIBRARY_PATH
/home/quorty/miniforge3/envs/poly/bin/launch_robot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
version: (git) 93bf7d5e056012707cd0be26282bf5e36e668db9
Warning: Failed to load 'libtorchscript_pinocchio.so' from CONDA_PREFIX, loading from default build directory instead: '/home/quorty/polymetis/irl_polymetis/polymetis/build/torch_isolation/libtorchscript_pinocchio.so'
Warning: Failed to load 'libtorchrot.so' from CONDA_PREFIX, loading from default build directory instead: '/home/quorty/polymetis/irl_polymetis/polymetis/build/torch_isolation/libtorchrot.so'
/home/quorty/miniforge3/envs/poly/lib/python3.9/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive robot_client/franka_hardware.yaml in file:///home/quorty/polymetis/irl_polymetis/polymetis/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
[2024-07-09 09:52:21,075][__main__][INFO] - Adding /home/quorty/polymetis/irl_polymetis/polymetis/build to $PATH
[2024-07-09 09:52:21,076][__main__][INFO] - Starting server
Traceback (most recent call last):
  File "/home/quorty/polymetis/irl_polymetis/polymetis/python/scripts/launch_robot.py", line 52, in main
    server_output = subprocess.Popen(
  File "/home/quorty/miniforge3/envs/poly/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/quorty/miniforge3/envs/poly/lib/python3.9/subprocess.py", line 1694, in _execute_child
    and os.path.dirname(executable)
  File "/home/quorty/miniforge3/envs/poly/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I have looked a bit into the files to check what might have gone wrong. It seems like the server executible from  `/irl_polymetis/polymetis/conf/launch_robot.yaml` called `run_server` is not found.

**Comment by quorty** [comment]
I deleted the `irl_polymetis/polymetis/build` folder and recompiled and rebuilt everything (just like in the readme):

```
# compile stuff
./scripts/build_libfranka.sh
mkdir -p ./polymetis/build
cd ./polymetis/build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_FRANKA=ON
make -j
cd ../..

# inside the project root
pip install -e ./polymetis
```

Now the script works.
