### ISSUE TITLE
Strarting Robot Server on Workstation PC / Installing NUC build on Workstation PC

### ISSUE THREAD

**Issue by quorty** [intuitive-robots/irl_polymetis#21]
Due to certain issues with the NUC, I have to temporarily start the robot server on my workstation PC. Since I have not installed the NUC build, the following error arises:

```
...
Traceback (most recent call last):
  File "/home/quorty/audio-pipeline/irl_polymetis/polymetis/python/scripts/launch_robot.py", line 75, in main
    client.run()
  File "/home/quorty/audio-pipeline/irl_polymetis/polymetis/python/polymetis/robot_client/executable_robot_client.py", line 69, in run
    assert path_to_exec, f"Unable to find binary {self.executable_cfg.exec}"
AssertionError: Unable to find binary franka_panda_client

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2024-08-05 11:00:37,513][__main__][INFO] - Killing subprocess with pid 11329, pgid 11329...
```

My question now is this: How can I add the NUC functionality on my workstation PC so that build issues are avoided?

**Comment by quorty** [comment]
It seems, that installing the NUC build is not going to solve my issue, since without the NUC PC I'm not going to be able to control the robots through Polymetis anyways. (This is the case for IRL atleast.)

Thanks Paul for the help!
